// AUTO-GENERATED — run: node scripts/generate-fixtures.mjs
// Source: 2026 Matches Schedule.xlsx

export type CompetitionGroup =
  | "Friendly"
  | "Premiership 2"
  | "Championship 2"
  | "Championship 4"
  | "Sunday League"
  | "CS Challenge Cup"
  | "Midweek Div 1"
  | "Midweek Div 3"
  | "Cup";

export interface Fixture {
  id: string;
  date: string;         // YYYY-MM-DD
  day: string;          // Monday … Sunday
  competition: string;  // exact name from spreadsheet
  competitionGroup: CompetitionGroup;
  overs: number;
  homeAway: "Home" | "Away";
  opponent: string;
  venue: string;
  startTime: string;    // HH:mm
  isWeekend: boolean;
  isT20: boolean;
  isFriendly: boolean;
  remarks: string;
  status: "upcoming" | "completed";
}

export const FIXTURES_2026: Fixture[] = [
  {
    "id": "fix-2026-04-18-friendly-(prem-2)-home",
    "date": "2026-04-18",
    "day": "Saturday",
    "competition": "Friendly (Prem 2)",
    "competitionGroup": "Friendly",
    "overs": 50,
    "homeAway": "Home",
    "opponent": "East Kilbride",
    "venue": "Bellahouston",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": true,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-04-19-friendly-(champ-2)-away",
    "date": "2026-04-19",
    "day": "Sunday",
    "competition": "Friendly (Champ 2)",
    "competitionGroup": "Friendly",
    "overs": 50,
    "homeAway": "Away",
    "opponent": "Ferguslie",
    "venue": "Ferguslie",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": true,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-04-25-friendly-(champ-2)-away",
    "date": "2026-04-25",
    "day": "Saturday",
    "competition": "Friendly (Champ 2)",
    "competitionGroup": "Friendly",
    "overs": 50,
    "homeAway": "Away",
    "opponent": "West of Scotland",
    "venue": "Partick",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": true,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-04-26-friendly-(prem-2)-home",
    "date": "2026-04-26",
    "day": "Sunday",
    "competition": "Friendly (Prem 2)",
    "competitionGroup": "Friendly",
    "overs": 50,
    "homeAway": "Home",
    "opponent": "East Kilbride",
    "venue": "New Williamfield 2",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": true,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-04-26-friendly-(champ-4)-home",
    "date": "2026-04-26",
    "day": "Sunday",
    "competition": "Friendly (Champ 4)",
    "competitionGroup": "Friendly",
    "overs": 50,
    "homeAway": "Home",
    "opponent": "Milngavie",
    "venue": "Bellahouston",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": true,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-05-02-premiership-2-away",
    "date": "2026-05-02",
    "day": "Saturday",
    "competition": "Premiership 2",
    "competitionGroup": "Premiership 2",
    "overs": 50,
    "homeAway": "Away",
    "opponent": "Stirling County",
    "venue": "New Williamfield 1",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-05-02-championship-2-home",
    "date": "2026-05-02",
    "day": "Saturday",
    "competition": "Championship 2",
    "competitionGroup": "Championship 2",
    "overs": 40,
    "homeAway": "Home",
    "opponent": "Meikleriggs",
    "venue": "Bellahouston",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-05-03-championship-4-home",
    "date": "2026-05-03",
    "day": "Sunday",
    "competition": "Championship 4",
    "competitionGroup": "Championship 4",
    "overs": 40,
    "homeAway": "Home",
    "opponent": "East Kilbride",
    "venue": "Bellahouston",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-05-06-mcculloch-cup-home",
    "date": "2026-05-06",
    "day": "Wednesday",
    "competition": "McCulloch Cup",
    "competitionGroup": "Cup",
    "overs": 20,
    "homeAway": "Home",
    "opponent": "Prestwick",
    "venue": "Torrance House",
    "startTime": "6:00",
    "isWeekend": false,
    "isT20": true,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-05-09-championship-2-away",
    "date": "2026-05-09",
    "day": "Saturday",
    "competition": "Championship 2",
    "competitionGroup": "Championship 2",
    "overs": 40,
    "homeAway": "Away",
    "opponent": "The Tryst",
    "venue": "The Tryst",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-05-09-premiership-2-home",
    "date": "2026-05-09",
    "day": "Saturday",
    "competition": "Premiership 2",
    "competitionGroup": "Premiership 2",
    "overs": 50,
    "homeAway": "Home",
    "opponent": "Langside",
    "venue": "New Williamfield 2",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-05-10-championship-4-home",
    "date": "2026-05-10",
    "day": "Sunday",
    "competition": "Championship 4",
    "competitionGroup": "Championship 4",
    "overs": 40,
    "homeAway": "Home",
    "opponent": "Kelburne 3",
    "venue": "Bellahouston",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-05-12-western-cup-home",
    "date": "2026-05-12",
    "day": "Tuesday",
    "competition": "Western Cup",
    "competitionGroup": "Cup",
    "overs": 20,
    "homeAway": "Home",
    "opponent": "Woodfarm",
    "venue": "Bellahouston",
    "startTime": "6:00",
    "isWeekend": false,
    "isT20": true,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-05-13-mcculloch-cup-away",
    "date": "2026-05-13",
    "day": "Wednesday",
    "competition": "McCulloch Cup",
    "competitionGroup": "Cup",
    "overs": 20,
    "homeAway": "Away",
    "opponent": "Kilmernock",
    "venue": "Kirkstyle",
    "startTime": "6:00",
    "isWeekend": false,
    "isT20": true,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-05-16-championship-2-away",
    "date": "2026-05-16",
    "day": "Saturday",
    "competition": "Championship 2",
    "competitionGroup": "Championship 2",
    "overs": 40,
    "homeAway": "Away",
    "opponent": "Hamilton Cresent",
    "venue": "New Williamfield 2",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-05-16-premiership-2-away",
    "date": "2026-05-16",
    "day": "Saturday",
    "competition": "Premiership 2",
    "competitionGroup": "Premiership 2",
    "overs": 50,
    "homeAway": "Away",
    "opponent": "Kilmernock",
    "venue": "Kirkstyle",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-05-17-championship-4-home",
    "date": "2026-05-17",
    "day": "Sunday",
    "competition": "Championship 4",
    "competitionGroup": "Championship 4",
    "overs": 40,
    "homeAway": "Home",
    "opponent": "Hillhead 3",
    "venue": "Bellahouston",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-05-19-western-cup-away",
    "date": "2026-05-19",
    "day": "Tuesday",
    "competition": "Western Cup",
    "competitionGroup": "Cup",
    "overs": 20,
    "homeAway": "Away",
    "opponent": "Bothwell",
    "venue": "Bothwell",
    "startTime": "6:00",
    "isWeekend": false,
    "isT20": true,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-05-20-mcculloch-cup-home",
    "date": "2026-05-20",
    "day": "Wednesday",
    "competition": "McCulloch Cup",
    "competitionGroup": "Cup",
    "overs": 20,
    "homeAway": "Home",
    "opponent": "Ayr",
    "venue": "Torrance House",
    "startTime": "6:00",
    "isWeekend": false,
    "isT20": true,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-05-23-championship-2-home",
    "date": "2026-05-23",
    "day": "Saturday",
    "competition": "Championship 2",
    "competitionGroup": "Championship 2",
    "overs": 40,
    "homeAway": "Home",
    "opponent": "Hughenden",
    "venue": "Bellahouston",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-05-23-championship-4-away",
    "date": "2026-05-23",
    "day": "Saturday",
    "competition": "Championship 4",
    "competitionGroup": "Championship 4",
    "overs": 40,
    "homeAway": "Away",
    "opponent": "Inverclyde",
    "venue": "Gourock Park",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-05-23-premiership-2-home",
    "date": "2026-05-23",
    "day": "Saturday",
    "competition": "Premiership 2",
    "competitionGroup": "Premiership 2",
    "overs": 50,
    "homeAway": "Home",
    "opponent": "Dumfries",
    "venue": "New Williamfield 2",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-05-24-sunday-league-div-1-away",
    "date": "2026-05-24",
    "day": "Sunday",
    "competition": "Sunday League Div 1",
    "competitionGroup": "Sunday League",
    "overs": 40,
    "homeAway": "Away",
    "opponent": "Hillend",
    "venue": "Glenpark",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-05-24-cs-challenge-cup-home",
    "date": "2026-05-24",
    "day": "Sunday",
    "competition": "CS Challenge Cup",
    "competitionGroup": "CS Challenge Cup",
    "overs": 40,
    "homeAway": "Home",
    "opponent": "Northern Counties",
    "venue": "New Williamfield 2",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-05-26-western-cup-away",
    "date": "2026-05-26",
    "day": "Tuesday",
    "competition": "Western Cup",
    "competitionGroup": "Cup",
    "overs": 20,
    "homeAway": "Away",
    "opponent": "Motherwell",
    "venue": "Danziel Park",
    "startTime": "6:00",
    "isWeekend": false,
    "isT20": true,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-05-28-rowan-cup-away",
    "date": "2026-05-28",
    "day": "Thursday",
    "competition": "Rowan Cup",
    "competitionGroup": "Cup",
    "overs": 20,
    "homeAway": "Away",
    "opponent": "Langside",
    "venue": "Albert Park",
    "startTime": "6:00",
    "isWeekend": false,
    "isT20": true,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-05-30-premiership-2-away",
    "date": "2026-05-30",
    "day": "Saturday",
    "competition": "Premiership 2",
    "competitionGroup": "Premiership 2",
    "overs": 50,
    "homeAway": "Away",
    "opponent": "Hillhead",
    "venue": "Hughenden",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-05-30-championship-2-away",
    "date": "2026-05-30",
    "day": "Saturday",
    "competition": "Championship 2",
    "competitionGroup": "Championship 2",
    "overs": 40,
    "homeAway": "Away",
    "opponent": "Anniesland",
    "venue": "New Anniesland",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-05-31-championship-4-home",
    "date": "2026-05-31",
    "day": "Sunday",
    "competition": "Championship 4",
    "competitionGroup": "Championship 4",
    "overs": 40,
    "homeAway": "Home",
    "opponent": "Clydesdale Cavaliers",
    "venue": "Bellahouston",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-06-02-western-cup-away",
    "date": "2026-06-02",
    "day": "Tuesday",
    "competition": "Western Cup",
    "competitionGroup": "Cup",
    "overs": 20,
    "homeAway": "Away",
    "opponent": "Titwood",
    "venue": "Titwood",
    "startTime": "6:00",
    "isWeekend": false,
    "isT20": true,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-06-04-greenwood-trophy-home",
    "date": "2026-06-04",
    "day": "Thursday",
    "competition": "Greenwood Trophy",
    "competitionGroup": "Cup",
    "overs": 20,
    "homeAway": "Home",
    "opponent": "Meikleriggs",
    "venue": "Bellahouston",
    "startTime": "6:00",
    "isWeekend": false,
    "isT20": true,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-06-06-championship-2-home",
    "date": "2026-06-06",
    "day": "Saturday",
    "competition": "Championship 2",
    "competitionGroup": "Championship 2",
    "overs": 40,
    "homeAway": "Home",
    "opponent": "Glenpark",
    "venue": "Bellahouston",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-06-06-premiership-2-home",
    "date": "2026-06-06",
    "day": "Saturday",
    "competition": "Premiership 2",
    "competitionGroup": "Premiership 2",
    "overs": 50,
    "homeAway": "Home",
    "opponent": "East Kilbride",
    "venue": "New Williamfield 2",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-06-07-championship-4-away",
    "date": "2026-06-07",
    "day": "Sunday",
    "competition": "Championship 4",
    "competitionGroup": "Championship 4",
    "overs": 40,
    "homeAway": "Away",
    "opponent": "Milngavie 3rd",
    "venue": "Garscube",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-06-09-midweek-div-1-home",
    "date": "2026-06-09",
    "day": "Tuesday",
    "competition": "Midweek Div 1",
    "competitionGroup": "Midweek Div 1",
    "overs": 20,
    "homeAway": "Home",
    "opponent": "Milngavie",
    "venue": "Bellahouston",
    "startTime": "6:00",
    "isWeekend": false,
    "isT20": true,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-06-09-western-cup-away",
    "date": "2026-06-09",
    "day": "Tuesday",
    "competition": "Western Cup",
    "competitionGroup": "Cup",
    "overs": 20,
    "homeAway": "Away",
    "opponent": "Langloan",
    "venue": "Langloan, Coatbridge",
    "startTime": "6:00",
    "isWeekend": false,
    "isT20": true,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-06-10-midweek-div-3-home",
    "date": "2026-06-10",
    "day": "Wednesday",
    "competition": "Midweek Div 3",
    "competitionGroup": "Midweek Div 3",
    "overs": 20,
    "homeAway": "Home",
    "opponent": "Galloway",
    "venue": "Bellahouston",
    "startTime": "6:00",
    "isWeekend": false,
    "isT20": true,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-06-13-championship-2-away",
    "date": "2026-06-13",
    "day": "Saturday",
    "competition": "Championship 2",
    "competitionGroup": "Championship 2",
    "overs": 40,
    "homeAway": "Away",
    "opponent": "Albert Park",
    "venue": "Albert Park",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-06-13-premiership-2-home",
    "date": "2026-06-13",
    "day": "Saturday",
    "competition": "Premiership 2",
    "competitionGroup": "Premiership 2",
    "overs": 50,
    "homeAway": "Home",
    "opponent": "Helensburgh",
    "venue": "New Williamfield 2",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-06-14-championship-4-home",
    "date": "2026-06-14",
    "day": "Sunday",
    "competition": "Championship 4",
    "competitionGroup": "Championship 4",
    "overs": 40,
    "homeAway": "Home",
    "opponent": "Bute County & Cowal",
    "venue": "Bellahouston",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-06-14-sunday-league-div-1-away",
    "date": "2026-06-14",
    "day": "Sunday",
    "competition": "Sunday League Div 1",
    "competitionGroup": "Sunday League",
    "overs": 40,
    "homeAway": "Away",
    "opponent": "Shimla Cottage Drumpellier",
    "venue": "Langloan, Coatbridge",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-06-16-midweek-div-1-away",
    "date": "2026-06-16",
    "day": "Tuesday",
    "competition": "Midweek Div 1",
    "competitionGroup": "Midweek Div 1",
    "overs": 20,
    "homeAway": "Away",
    "opponent": "Glasgow Accies",
    "venue": "Old Anniesland",
    "startTime": "6:00",
    "isWeekend": false,
    "isT20": true,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-06-16-midweek-div-3-home",
    "date": "2026-06-16",
    "day": "Tuesday",
    "competition": "Midweek Div 3",
    "competitionGroup": "Midweek Div 3",
    "overs": 20,
    "homeAway": "Home",
    "opponent": "BBC Scotland",
    "venue": "Bellahouston",
    "startTime": "6:00",
    "isWeekend": false,
    "isT20": true,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-06-20-championship-4-away",
    "date": "2026-06-20",
    "day": "Saturday",
    "competition": "Championship 4",
    "competitionGroup": "Championship 4",
    "overs": 40,
    "homeAway": "Away",
    "opponent": "Kingholm",
    "venue": "Kingholm Park",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-06-20-premiership-2-home",
    "date": "2026-06-20",
    "day": "Saturday",
    "competition": "Premiership 2",
    "competitionGroup": "Premiership 2",
    "overs": 50,
    "homeAway": "Home",
    "opponent": "Uddingston",
    "venue": "New Williamfield 2",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-06-20-championship-2-home",
    "date": "2026-06-20",
    "day": "Saturday",
    "competition": "Championship 2",
    "competitionGroup": "Championship 2",
    "overs": 40,
    "homeAway": "Home",
    "opponent": "Nunholm",
    "venue": "Bellahouston",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-06-23-midweek-div-3-away",
    "date": "2026-06-23",
    "day": "Tuesday",
    "competition": "Midweek Div 3",
    "competitionGroup": "Midweek Div 3",
    "overs": 20,
    "homeAway": "Away",
    "opponent": "Vale of Laven",
    "venue": "Milburn Park",
    "startTime": "6:00",
    "isWeekend": false,
    "isT20": true,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-06-23-midweek-div-1-away",
    "date": "2026-06-23",
    "day": "Tuesday",
    "competition": "Midweek Div 1",
    "competitionGroup": "Midweek Div 1",
    "overs": 20,
    "homeAway": "Away",
    "opponent": "Victoria",
    "venue": "Bellahouston",
    "startTime": "6:00",
    "isWeekend": false,
    "isT20": true,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-06-27-championship-4-home",
    "date": "2026-06-27",
    "day": "Saturday",
    "competition": "Championship 4",
    "competitionGroup": "Championship 4",
    "overs": 40,
    "homeAway": "Home",
    "opponent": "Ardencaple",
    "venue": "HPG",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "Move to HPG as Bella not available",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-06-27-premiership-2-away",
    "date": "2026-06-27",
    "day": "Saturday",
    "competition": "Premiership 2",
    "competitionGroup": "Premiership 2",
    "overs": 50,
    "homeAway": "Away",
    "opponent": "Greenock",
    "venue": "Glenpark",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-06-27-championship-2-away",
    "date": "2026-06-27",
    "day": "Saturday",
    "competition": "Championship 2",
    "competitionGroup": "Championship 2",
    "overs": 40,
    "homeAway": "Away",
    "opponent": "Torrance House",
    "venue": "Torrance House",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-06-28-sunday-league-div-1-home",
    "date": "2026-06-28",
    "day": "Sunday",
    "competition": "Sunday League Div 1",
    "competitionGroup": "Sunday League",
    "overs": 40,
    "homeAway": "Home",
    "opponent": "Hillend",
    "venue": "New Williamfield 2",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "Need to book Striling as Bella not available",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-06-30-midweek-div-3-home",
    "date": "2026-06-30",
    "day": "Tuesday",
    "competition": "Midweek Div 3",
    "competitionGroup": "Midweek Div 3",
    "overs": 20,
    "homeAway": "Home",
    "opponent": "Bees",
    "venue": "HPG",
    "startTime": "6:00",
    "isWeekend": false,
    "isT20": true,
    "isFriendly": false,
    "remarks": "Move to HPG as Bella not available",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-07-01-midweek-div-1-home",
    "date": "2026-07-01",
    "day": "Wednesday",
    "competition": "Midweek Div 1",
    "competitionGroup": "Midweek Div 1",
    "overs": 20,
    "homeAway": "Home",
    "opponent": "Renfrew",
    "venue": "HPG",
    "startTime": "6:00",
    "isWeekend": false,
    "isT20": true,
    "isFriendly": false,
    "remarks": "Move to HPG as Bella not available",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-07-04-premiership-2-home",
    "date": "2026-07-04",
    "day": "Saturday",
    "competition": "Premiership 2",
    "competitionGroup": "Premiership 2",
    "overs": 50,
    "homeAway": "Home",
    "opponent": "Stirling County",
    "venue": "New Williamfield 2",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-07-04-championship-2-away",
    "date": "2026-07-04",
    "day": "Saturday",
    "competition": "Championship 2",
    "competitionGroup": "Championship 2",
    "overs": 40,
    "homeAway": "Away",
    "opponent": "Meikleriggs",
    "venue": "Meikleriggs",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-07-05-championship-4-away",
    "date": "2026-07-05",
    "day": "Sunday",
    "competition": "Championship 4",
    "competitionGroup": "Championship 4",
    "overs": 40,
    "homeAway": "Away",
    "opponent": "East Kilbride 3",
    "venue": "Torrance House",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-07-05-sunday-league-div-1-away",
    "date": "2026-07-05",
    "day": "Sunday",
    "competition": "Sunday League Div 1",
    "competitionGroup": "Sunday League",
    "overs": 40,
    "homeAway": "Away",
    "opponent": "Stenhousemuir CC",
    "venue": "The Tryst",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-07-07-midweek-div-3-home",
    "date": "2026-07-07",
    "day": "Tuesday",
    "competition": "Midweek Div 3",
    "competitionGroup": "Midweek Div 3",
    "overs": 20,
    "homeAway": "Home",
    "opponent": "JP Morgan",
    "venue": "Bellahouston",
    "startTime": "6:00",
    "isWeekend": false,
    "isT20": true,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-07-07-midweek-div-1-away",
    "date": "2026-07-07",
    "day": "Tuesday",
    "competition": "Midweek Div 1",
    "competitionGroup": "Midweek Div 1",
    "overs": 20,
    "homeAway": "Away",
    "opponent": "Cambusdoon",
    "venue": "Cambusdoon",
    "startTime": "6:00",
    "isWeekend": false,
    "isT20": true,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-07-11-premiership-2-away",
    "date": "2026-07-11",
    "day": "Saturday",
    "competition": "Premiership 2",
    "competitionGroup": "Premiership 2",
    "overs": 50,
    "homeAway": "Away",
    "opponent": "Langside",
    "venue": "Albert Park",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-07-11-championship-2-home",
    "date": "2026-07-11",
    "day": "Saturday",
    "competition": "Championship 2",
    "competitionGroup": "Championship 2",
    "overs": 40,
    "homeAway": "Home",
    "opponent": "The Tryst",
    "venue": "Bellahouston",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-07-12-championship-4-away",
    "date": "2026-07-12",
    "day": "Sunday",
    "competition": "Championship 4",
    "competitionGroup": "Championship 4",
    "overs": 40,
    "homeAway": "Away",
    "opponent": "Kelburne 3",
    "venue": "Kelburne",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-07-14-midweek-div-3-away",
    "date": "2026-07-14",
    "day": "Tuesday",
    "competition": "Midweek Div 3",
    "competitionGroup": "Midweek Div 3",
    "overs": 20,
    "homeAway": "Away",
    "opponent": "GHK",
    "venue": "Old Anniesland",
    "startTime": "6:00",
    "isWeekend": false,
    "isT20": true,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-07-15-midweek-div-1-away",
    "date": "2026-07-15",
    "day": "Wednesday",
    "competition": "Midweek Div 1",
    "competitionGroup": "Midweek Div 1",
    "overs": 20,
    "homeAway": "Away",
    "opponent": "GHK Strathclyde",
    "venue": "Old Anniesland",
    "startTime": "6:00",
    "isWeekend": false,
    "isT20": true,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-07-18-championship-2-home",
    "date": "2026-07-18",
    "day": "Saturday",
    "competition": "Championship 2",
    "competitionGroup": "Championship 2",
    "overs": 40,
    "homeAway": "Home",
    "opponent": "Hamilton Cresent",
    "venue": "Bellahouston",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-07-18-premiership-2-home",
    "date": "2026-07-18",
    "day": "Saturday",
    "competition": "Premiership 2",
    "competitionGroup": "Premiership 2",
    "overs": 50,
    "homeAway": "Home",
    "opponent": "Kilmernock",
    "venue": "New Williamfield 2",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-07-19-championship-4-away",
    "date": "2026-07-19",
    "day": "Sunday",
    "competition": "Championship 4",
    "competitionGroup": "Championship 4",
    "overs": 40,
    "homeAway": "Away",
    "opponent": "Hillhead 3",
    "venue": "Hughenden",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-07-19-sunday-league-div-1-away",
    "date": "2026-07-19",
    "day": "Sunday",
    "competition": "Sunday League Div 1",
    "competitionGroup": "Sunday League",
    "overs": 40,
    "homeAway": "Away",
    "opponent": "Shimla Cottage Drumpellier",
    "venue": "Langloan, Coatbridge",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-07-22-midweek-div-1-home",
    "date": "2026-07-22",
    "day": "Wednesday",
    "competition": "Midweek Div 1",
    "competitionGroup": "Midweek Div 1",
    "overs": 20,
    "homeAway": "Home",
    "opponent": "Uddingston",
    "venue": "Bellahouston",
    "startTime": "6:00",
    "isWeekend": false,
    "isT20": true,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-07-23-midweek-div-3-home",
    "date": "2026-07-23",
    "day": "Thursday",
    "competition": "Midweek Div 3",
    "competitionGroup": "Midweek Div 3",
    "overs": 20,
    "homeAway": "Home",
    "opponent": "Ferguslie",
    "venue": "Bellahouston",
    "startTime": "6:00",
    "isWeekend": false,
    "isT20": true,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-07-25-championship-2-away",
    "date": "2026-07-25",
    "day": "Saturday",
    "competition": "Championship 2",
    "competitionGroup": "Championship 2",
    "overs": 40,
    "homeAway": "Away",
    "opponent": "Hughenden",
    "venue": "Hughenden",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-07-25-premiership-2-away",
    "date": "2026-07-25",
    "day": "Saturday",
    "competition": "Premiership 2",
    "competitionGroup": "Premiership 2",
    "overs": 50,
    "homeAway": "Away",
    "opponent": "Dumfries",
    "venue": "Nunholm",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-07-26-championship-4-home",
    "date": "2026-07-26",
    "day": "Sunday",
    "competition": "Championship 4",
    "competitionGroup": "Championship 4",
    "overs": 40,
    "homeAway": "Home",
    "opponent": "Inverclyde",
    "venue": "Bellahouston",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-07-28-midweek-div-3-away",
    "date": "2026-07-28",
    "day": "Tuesday",
    "competition": "Midweek Div 3",
    "competitionGroup": "Midweek Div 3",
    "overs": 20,
    "homeAway": "Away",
    "opponent": "Torrance House",
    "venue": "Torrance House",
    "startTime": "6:00",
    "isWeekend": false,
    "isT20": true,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-08-01-championship-2-home",
    "date": "2026-08-01",
    "day": "Saturday",
    "competition": "Championship 2",
    "competitionGroup": "Championship 2",
    "overs": 40,
    "homeAway": "Home",
    "opponent": "Anniesland",
    "venue": "Bellahouston",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-08-01-premiership-2-home",
    "date": "2026-08-01",
    "day": "Saturday",
    "competition": "Premiership 2",
    "competitionGroup": "Premiership 2",
    "overs": 50,
    "homeAway": "Home",
    "opponent": "Hillhead",
    "venue": "New Williamfield 2",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-08-02-sunday-league-div-1-away",
    "date": "2026-08-02",
    "day": "Sunday",
    "competition": "Sunday League Div 1",
    "competitionGroup": "Sunday League",
    "overs": 40,
    "homeAway": "Away",
    "opponent": "Kelburne CC",
    "venue": "Whitehaugh",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-08-02-championship-4-away",
    "date": "2026-08-02",
    "day": "Sunday",
    "competition": "Championship 4",
    "competitionGroup": "Championship 4",
    "overs": 40,
    "homeAway": "Away",
    "opponent": "Clydesdale Cavaliers",
    "venue": "Titwood",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-08-04-midweek-div-3-home",
    "date": "2026-08-04",
    "day": "Tuesday",
    "competition": "Midweek Div 3",
    "competitionGroup": "Midweek Div 3",
    "overs": 20,
    "homeAway": "Home",
    "opponent": "Milngavie",
    "venue": "Bellahouston",
    "startTime": "6:00",
    "isWeekend": false,
    "isT20": true,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-08-08-championship-2-away",
    "date": "2026-08-08",
    "day": "Saturday",
    "competition": "Championship 2",
    "competitionGroup": "Championship 2",
    "overs": 40,
    "homeAway": "Away",
    "opponent": "Glenpark",
    "venue": "Glenpark",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-08-08-premiership-2-away",
    "date": "2026-08-08",
    "day": "Saturday",
    "competition": "Premiership 2",
    "competitionGroup": "Premiership 2",
    "overs": 50,
    "homeAway": "Away",
    "opponent": "East Kilbride",
    "venue": "Torrance House",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-08-08-championship-4-home",
    "date": "2026-08-08",
    "day": "Saturday",
    "competition": "Championship 4",
    "competitionGroup": "Championship 4",
    "overs": 40,
    "homeAway": "Home",
    "opponent": "Milngavie 3rd",
    "venue": "Bellahouston",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-08-09-sunday-league-div-1-home",
    "date": "2026-08-09",
    "day": "Monday",
    "competition": "Sunday League Div 1",
    "competitionGroup": "Sunday League",
    "overs": 40,
    "homeAway": "Home",
    "opponent": "Kenburne CC",
    "venue": "Bellahouston",
    "startTime": "12:00",
    "isWeekend": false,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-08-11-midweek-div-3-home",
    "date": "2026-08-11",
    "day": "Tuesday",
    "competition": "Midweek Div 3",
    "competitionGroup": "Midweek Div 3",
    "overs": 20,
    "homeAway": "Home",
    "opponent": "Kilmernock",
    "venue": "Bellahouston",
    "startTime": "6:00",
    "isWeekend": false,
    "isT20": true,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-08-15-championship-2-home",
    "date": "2026-08-15",
    "day": "Saturday",
    "competition": "Championship 2",
    "competitionGroup": "Championship 2",
    "overs": 40,
    "homeAway": "Home",
    "opponent": "Albert Park",
    "venue": "Bellahouston",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-08-15-premiership-2-away",
    "date": "2026-08-15",
    "day": "Saturday",
    "competition": "Premiership 2",
    "competitionGroup": "Premiership 2",
    "overs": 50,
    "homeAway": "Away",
    "opponent": "Helensburgh",
    "venue": "Ardencaple",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-08-15-championship-4-away",
    "date": "2026-08-15",
    "day": "Saturday",
    "competition": "Championship 4",
    "competitionGroup": "Championship 4",
    "overs": 40,
    "homeAway": "Away",
    "opponent": "Bute County & Cowal",
    "venue": "Bute",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-08-16-sunday-league-div-1-away",
    "date": "2026-08-16",
    "day": "Sunday",
    "competition": "Sunday League Div 1",
    "competitionGroup": "Sunday League",
    "overs": 40,
    "homeAway": "Away",
    "opponent": "Stenhousemuir CC",
    "venue": "The Tryst",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-08-18-midweek-div-3-away",
    "date": "2026-08-18",
    "day": "Tuesday",
    "competition": "Midweek Div 3",
    "competitionGroup": "Midweek Div 3",
    "overs": 20,
    "homeAway": "Away",
    "opponent": "Hillend",
    "venue": "Glenpark",
    "startTime": "6:00",
    "isWeekend": false,
    "isT20": true,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-08-22-championship-2-away",
    "date": "2026-08-22",
    "day": "Saturday",
    "competition": "Championship 2",
    "competitionGroup": "Championship 2",
    "overs": 40,
    "homeAway": "Away",
    "opponent": "Nunholm",
    "venue": "Nunholm",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-08-22-premiership-2-away",
    "date": "2026-08-22",
    "day": "Saturday",
    "competition": "Premiership 2",
    "competitionGroup": "Premiership 2",
    "overs": 50,
    "homeAway": "Away",
    "opponent": "Uddingston",
    "venue": "Uddingston",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-08-23-championship-4-home",
    "date": "2026-08-23",
    "day": "Sunday",
    "competition": "Championship 4",
    "competitionGroup": "Championship 4",
    "overs": 40,
    "homeAway": "Home",
    "opponent": "Kingholm",
    "venue": "Bellahouston",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-08-29-championship-2-home",
    "date": "2026-08-29",
    "day": "Saturday",
    "competition": "Championship 2",
    "competitionGroup": "Championship 2",
    "overs": 40,
    "homeAway": "Home",
    "opponent": "Torrance House",
    "venue": "Bellahouston",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-08-29-premiership-2-home",
    "date": "2026-08-29",
    "day": "Saturday",
    "competition": "Premiership 2",
    "competitionGroup": "Premiership 2",
    "overs": 50,
    "homeAway": "Home",
    "opponent": "Greenock",
    "venue": "New Williamfield 2",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-08-29-championship-4-away",
    "date": "2026-08-29",
    "day": "Saturday",
    "competition": "Championship 4",
    "competitionGroup": "Championship 4",
    "overs": 40,
    "homeAway": "Away",
    "opponent": "Ardencaple",
    "venue": "Ardencaple",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": false,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-09-05-friendly-home",
    "date": "2026-09-05",
    "day": "Saturday",
    "competition": "Friendly",
    "competitionGroup": "Friendly",
    "overs": 40,
    "homeAway": "Home",
    "opponent": "TBD",
    "venue": "Bellahouston",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": true,
    "remarks": "",
    "status": "upcoming"
  },
  {
    "id": "fix-2026-09-06-friendly-home",
    "date": "2026-09-06",
    "day": "Sunday",
    "competition": "Friendly",
    "competitionGroup": "Friendly",
    "overs": 40,
    "homeAway": "Home",
    "opponent": "TBD",
    "venue": "Bellahouston",
    "startTime": "12:00",
    "isWeekend": true,
    "isT20": false,
    "isFriendly": true,
    "remarks": "",
    "status": "upcoming"
  }
];

export const COMPETITION_GROUPS: CompetitionGroup[] = [
  "Premiership 2",
  "Championship 2",
  "Championship 4",
  "Sunday League",
  "CS Challenge Cup",
  "Midweek Div 1",
  "Midweek Div 3",
  "Cup",
  "Friendly",
];
