// AUTO-GENERATED — run: node scripts/generate-players.mjs
// Source: MCC-Players-For-AI.xlsx

export type PlayerRole = "Batter" | "Bowler" | "All-rounder";
export type PlayerStatus = "Active" | "Inactive";

export interface Player {
  id: string;
  name: string;
  preferredName: string;
  /** 1 = highest ability, 4 = developmental */
  teamLevel: number;
  role: PlayerRole;
  /** 0–10 */
  battingRating: number;
  /** 0–10 */
  bowlingRating: number;
  isWicketkeeper: boolean;
  isCaptain: boolean;
  photoUrl: string;
  status: PlayerStatus;
}

export const PLAYERS: Player[] = [
  {
    "id": "001",
    "name": "Rohitabja Haldar",
    "preferredName": "Rohit",
    "teamLevel": 1,
    "role": "Batter",
    "battingRating": 8,
    "bowlingRating": 2,
    "isWicketkeeper": false,
    "isCaptain": true,
    "photoUrl": "https://image-url.com",
    "status": "Active"
  },
  {
    "id": "002",
    "name": "Simon Machado",
    "preferredName": "Simon",
    "teamLevel": 1,
    "role": "All-rounder",
    "battingRating": 9,
    "bowlingRating": 6,
    "isWicketkeeper": false,
    "isCaptain": false,
    "photoUrl": "https://image-url.com",
    "status": "Active"
  },
  {
    "id": "003",
    "name": "Akshay Hudar",
    "preferredName": "Akshay",
    "teamLevel": 1,
    "role": "Batter",
    "battingRating": 9,
    "bowlingRating": 2,
    "isWicketkeeper": false,
    "isCaptain": false,
    "photoUrl": "https://image-url.com",
    "status": "Active"
  },
  {
    "id": "004",
    "name": "Rahul Kambhampati",
    "preferredName": "Rahul",
    "teamLevel": 1,
    "role": "Batter",
    "battingRating": 8,
    "bowlingRating": 2,
    "isWicketkeeper": true,
    "isCaptain": false,
    "photoUrl": "https://image-url.com",
    "status": "Active"
  },
  {
    "id": "005",
    "name": "Shahnawaz Akhtar",
    "preferredName": "Shahnawaz",
    "teamLevel": 1,
    "role": "All-rounder",
    "battingRating": 7,
    "bowlingRating": 8,
    "isWicketkeeper": false,
    "isCaptain": false,
    "photoUrl": "https://image-url.com",
    "status": "Active"
  },
  {
    "id": "006",
    "name": "Balakrishna Devineni",
    "preferredName": "Bala",
    "teamLevel": 1,
    "role": "Bowler",
    "battingRating": 4,
    "bowlingRating": 7,
    "isWicketkeeper": false,
    "isCaptain": false,
    "photoUrl": "https://image-url.com",
    "status": "Active"
  },
  {
    "id": "007",
    "name": "Rajat Dhar",
    "preferredName": "Rajat",
    "teamLevel": 1,
    "role": "All-rounder",
    "battingRating": 8,
    "bowlingRating": 5,
    "isWicketkeeper": false,
    "isCaptain": false,
    "photoUrl": "https://image-url.com",
    "status": "Active"
  },
  {
    "id": "008",
    "name": "Anish Gadgil",
    "preferredName": "Anish",
    "teamLevel": 1,
    "role": "Bowler",
    "battingRating": 3,
    "bowlingRating": 9,
    "isWicketkeeper": false,
    "isCaptain": false,
    "photoUrl": "https://image-url.com",
    "status": "Active"
  },
  {
    "id": "009",
    "name": "Anshu Kapila",
    "preferredName": "Anshu",
    "teamLevel": 1,
    "role": "Batter",
    "battingRating": 7,
    "bowlingRating": 4,
    "isWicketkeeper": false,
    "isCaptain": false,
    "photoUrl": "https://image-url.com",
    "status": "Active"
  },
  {
    "id": "010",
    "name": "Deepak Kumar",
    "preferredName": "Deepak",
    "teamLevel": 1,
    "role": "Bowler",
    "battingRating": 3,
    "bowlingRating": 8,
    "isWicketkeeper": false,
    "isCaptain": false,
    "photoUrl": "https://image-url.com",
    "status": "Active"
  },
  {
    "id": "011",
    "name": "Sushant Zanjure",
    "preferredName": "Sushant",
    "teamLevel": 1,
    "role": "All-rounder",
    "battingRating": 7,
    "bowlingRating": 5,
    "isWicketkeeper": false,
    "isCaptain": false,
    "photoUrl": "https://image-url.com",
    "status": "Active"
  },
  {
    "id": "012",
    "name": "Karthick Gurusamy",
    "preferredName": "Karthick",
    "teamLevel": 2,
    "role": "Bowler",
    "battingRating": 3,
    "bowlingRating": 7,
    "isWicketkeeper": false,
    "isCaptain": false,
    "photoUrl": "https://image-url.com",
    "status": "Active"
  },
  {
    "id": "013",
    "name": "Rahul Jagdale",
    "preferredName": "Rahul",
    "teamLevel": 2,
    "role": "All-rounder",
    "battingRating": 6,
    "bowlingRating": 5,
    "isWicketkeeper": false,
    "isCaptain": false,
    "photoUrl": "https://image-url.com",
    "status": "Active"
  },
  {
    "id": "014",
    "name": "Anulome kishore",
    "preferredName": "Anulome",
    "teamLevel": 2,
    "role": "Batter",
    "battingRating": 7,
    "bowlingRating": 3,
    "isWicketkeeper": false,
    "isCaptain": false,
    "photoUrl": "https://image-url.com",
    "status": "Active"
  },
  {
    "id": "015",
    "name": "Pradipta Mohanty",
    "preferredName": "Pradipta",
    "teamLevel": 2,
    "role": "Batter",
    "battingRating": 7,
    "bowlingRating": 1,
    "isWicketkeeper": false,
    "isCaptain": false,
    "photoUrl": "https://image-url.com",
    "status": "Active"
  },
  {
    "id": "016",
    "name": "August Pandey",
    "preferredName": "August",
    "teamLevel": 2,
    "role": "Bowler",
    "battingRating": 5,
    "bowlingRating": 7,
    "isWicketkeeper": false,
    "isCaptain": false,
    "photoUrl": "https://image-url.com",
    "status": "Active"
  },
  {
    "id": "017",
    "name": "Senthilkumar Ramasamy",
    "preferredName": "Senthil",
    "teamLevel": 2,
    "role": "Batter",
    "battingRating": 7,
    "bowlingRating": 2,
    "isWicketkeeper": true,
    "isCaptain": true,
    "photoUrl": "https://image-url.com",
    "status": "Active"
  },
  {
    "id": "018",
    "name": "Abhay Singh",
    "preferredName": "Abhay",
    "teamLevel": 2,
    "role": "Bowler",
    "battingRating": 4,
    "bowlingRating": 6,
    "isWicketkeeper": false,
    "isCaptain": false,
    "photoUrl": "https://image-url.com",
    "status": "Active"
  },
  {
    "id": "019",
    "name": "Siddharth Wadhwani",
    "preferredName": "Sid",
    "teamLevel": 2,
    "role": "Bowler",
    "battingRating": 6,
    "bowlingRating": 6,
    "isWicketkeeper": false,
    "isCaptain": false,
    "photoUrl": "https://image-url.com",
    "status": "Active"
  },
  {
    "id": "020",
    "name": "Abhisek Acharya",
    "preferredName": "Abhisek",
    "teamLevel": 3,
    "role": "Bowler",
    "battingRating": 3,
    "bowlingRating": 5,
    "isWicketkeeper": false,
    "isCaptain": false,
    "photoUrl": "https://image-url.com",
    "status": "Active"
  },
  {
    "id": "021",
    "name": "Aman Ahlawat",
    "preferredName": "Aman",
    "teamLevel": 3,
    "role": "Bowler",
    "battingRating": 3,
    "bowlingRating": 5,
    "isWicketkeeper": false,
    "isCaptain": false,
    "photoUrl": "https://image-url.com",
    "status": "Active"
  },
  {
    "id": "022",
    "name": "Akshay Bharadwaj",
    "preferredName": "Akshay",
    "teamLevel": 3,
    "role": "Bowler",
    "battingRating": 3,
    "bowlingRating": 5,
    "isWicketkeeper": false,
    "isCaptain": false,
    "photoUrl": "https://image-url.com",
    "status": "Active"
  },
  {
    "id": "023",
    "name": "Tejas Bharati",
    "preferredName": "Tejas",
    "teamLevel": 3,
    "role": "Bowler",
    "battingRating": 3,
    "bowlingRating": 4,
    "isWicketkeeper": false,
    "isCaptain": false,
    "photoUrl": "https://image-url.com",
    "status": "Active"
  },
  {
    "id": "024",
    "name": "Sandeep Bhat",
    "preferredName": "Sandeep",
    "teamLevel": 3,
    "role": "Batter",
    "battingRating": 5,
    "bowlingRating": 1,
    "isWicketkeeper": false,
    "isCaptain": false,
    "photoUrl": "https://image-url.com",
    "status": "Active"
  },
  {
    "id": "025",
    "name": "Ranjan Choudhury",
    "preferredName": "Ranjan",
    "teamLevel": 3,
    "role": "Batter",
    "battingRating": 6,
    "bowlingRating": 1,
    "isWicketkeeper": false,
    "isCaptain": false,
    "photoUrl": "https://image-url.com",
    "status": "Active"
  },
  {
    "id": "026",
    "name": "Arvind Kumar Lakshmi Narasimhan",
    "preferredName": "Arvind",
    "teamLevel": 3,
    "role": "Bowler",
    "battingRating": 4,
    "bowlingRating": 4,
    "isWicketkeeper": false,
    "isCaptain": false,
    "photoUrl": "https://image-url.com",
    "status": "Active"
  },
  {
    "id": "027",
    "name": "Vijay Shankar Mallajosula Venkata",
    "preferredName": "Vijay",
    "teamLevel": 3,
    "role": "Batter",
    "battingRating": 5,
    "bowlingRating": 4,
    "isWicketkeeper": false,
    "isCaptain": false,
    "photoUrl": "https://image-url.com",
    "status": "Active"
  },
  {
    "id": "028",
    "name": "Jim McLaren",
    "preferredName": "Jim",
    "teamLevel": 3,
    "role": "Batter",
    "battingRating": 4,
    "bowlingRating": 1,
    "isWicketkeeper": true,
    "isCaptain": true,
    "photoUrl": "https://image-url.com",
    "status": "Active"
  },
  {
    "id": "029",
    "name": "Sunil Rao",
    "preferredName": "Sunil",
    "teamLevel": 3,
    "role": "Batter",
    "battingRating": 5,
    "bowlingRating": 0,
    "isWicketkeeper": true,
    "isCaptain": false,
    "photoUrl": "https://image-url.com",
    "status": "Active"
  },
  {
    "id": "030",
    "name": "Narasimha lal Sasank",
    "preferredName": "Lal",
    "teamLevel": 3,
    "role": "Bowler",
    "battingRating": 4,
    "bowlingRating": 5,
    "isWicketkeeper": false,
    "isCaptain": false,
    "photoUrl": "https://image-url.com",
    "status": "Active"
  },
  {
    "id": "031",
    "name": "Manish Singh",
    "preferredName": "Manish",
    "teamLevel": 3,
    "role": "Bowler",
    "battingRating": 5,
    "bowlingRating": 8,
    "isWicketkeeper": false,
    "isCaptain": true,
    "photoUrl": "https://image-url.com",
    "status": "Active"
  },
  {
    "id": "032",
    "name": "Abhinesh Desai",
    "preferredName": "Abhinesh",
    "teamLevel": 4,
    "role": "Bowler",
    "battingRating": 4,
    "bowlingRating": 2,
    "isWicketkeeper": false,
    "isCaptain": false,
    "photoUrl": "https://image-url.com",
    "status": "Active"
  },
  {
    "id": "033",
    "name": "Artaban Johnson Jeldi",
    "preferredName": "Artaban",
    "teamLevel": 4,
    "role": "Bowler",
    "battingRating": 4,
    "bowlingRating": 3,
    "isWicketkeeper": false,
    "isCaptain": false,
    "photoUrl": "https://image-url.com",
    "status": "Active"
  },
  {
    "id": "034",
    "name": "Kamal Kishor",
    "preferredName": "Kamal",
    "teamLevel": 4,
    "role": "Bowler",
    "battingRating": 4,
    "bowlingRating": 3,
    "isWicketkeeper": false,
    "isCaptain": false,
    "photoUrl": "https://image-url.com",
    "status": "Active"
  },
  {
    "id": "035",
    "name": "Pankaj Nagar",
    "preferredName": "Pankaj",
    "teamLevel": 4,
    "role": "Bowler",
    "battingRating": 5,
    "bowlingRating": 6,
    "isWicketkeeper": false,
    "isCaptain": false,
    "photoUrl": "https://image-url.com",
    "status": "Active"
  },
  {
    "id": "036",
    "name": "Anandbabu Naidu Chakrala Sethuram",
    "preferredName": "Babu",
    "teamLevel": 4,
    "role": "Batter",
    "battingRating": 4,
    "bowlingRating": 1,
    "isWicketkeeper": true,
    "isCaptain": false,
    "photoUrl": "https://image-url.com",
    "status": "Active"
  },
  {
    "id": "037",
    "name": "Saravana Rathinam",
    "preferredName": "Saravana",
    "teamLevel": 4,
    "role": "Bowler",
    "battingRating": 3,
    "bowlingRating": 4,
    "isWicketkeeper": false,
    "isCaptain": false,
    "photoUrl": "https://image-url.com",
    "status": "Active"
  },
  {
    "id": "038",
    "name": "Nitin Lawrance",
    "preferredName": "Nitin",
    "teamLevel": 3,
    "role": "Batter",
    "battingRating": 4,
    "bowlingRating": 2,
    "isWicketkeeper": true,
    "isCaptain": false,
    "photoUrl": "https://image-url.com",
    "status": "Active"
  },
  {
    "id": "039",
    "name": "Aditya Chandrashekar",
    "preferredName": "Aditya",
    "teamLevel": 3,
    "role": "Bowler",
    "battingRating": 4,
    "bowlingRating": 5,
    "isWicketkeeper": false,
    "isCaptain": false,
    "photoUrl": "https://image-url.com",
    "status": "Active"
  },
  {
    "id": "040",
    "name": "Akshay Gupta",
    "preferredName": "Akshay",
    "teamLevel": 2,
    "role": "All-rounder",
    "battingRating": 5,
    "bowlingRating": 6,
    "isWicketkeeper": false,
    "isCaptain": false,
    "photoUrl": "https://image-url.com",
    "status": "Active"
  },
  {
    "id": "041",
    "name": "Atul Anand",
    "preferredName": "Atul",
    "teamLevel": 3,
    "role": "All-rounder",
    "battingRating": 5,
    "bowlingRating": 4,
    "isWicketkeeper": false,
    "isCaptain": false,
    "photoUrl": "https://image-url.com",
    "status": "Active"
  },
  {
    "id": "042",
    "name": "Manju Kiran",
    "preferredName": "Manju",
    "teamLevel": 3,
    "role": "Batter",
    "battingRating": 4,
    "bowlingRating": 0,
    "isWicketkeeper": false,
    "isCaptain": false,
    "photoUrl": "https://image-url.com",
    "status": "Active"
  },
  {
    "id": "043",
    "name": "Prabhu Maruthaiappan",
    "preferredName": "Prabhu",
    "teamLevel": 4,
    "role": "Batter",
    "battingRating": 3,
    "bowlingRating": 0,
    "isWicketkeeper": false,
    "isCaptain": false,
    "photoUrl": "https://image-url.com",
    "status": "Active"
  },
  {
    "id": "044",
    "name": "Sudhir Vusikala",
    "preferredName": "Sudhir",
    "teamLevel": 4,
    "role": "Batter",
    "battingRating": 2,
    "bowlingRating": 0,
    "isWicketkeeper": false,
    "isCaptain": false,
    "photoUrl": "https://image-url.com",
    "status": "Active"
  },
  {
    "id": "045",
    "name": "Naman Sangari",
    "preferredName": "Naman",
    "teamLevel": 4,
    "role": "Batter",
    "battingRating": 4,
    "bowlingRating": 0,
    "isWicketkeeper": true,
    "isCaptain": false,
    "photoUrl": "https://image-url.com",
    "status": "Active"
  },
  {
    "id": "046",
    "name": "Shouvonik Pal",
    "preferredName": "Shouvonik",
    "teamLevel": 2,
    "role": "All-rounder",
    "battingRating": 7,
    "bowlingRating": 7,
    "isWicketkeeper": false,
    "isCaptain": false,
    "photoUrl": "https://image-url.com",
    "status": "Active"
  }
];
